---
title: "Intro to Data & Probability - Project Rubric"
output: 
  html_document: 
    fig_height: 4
    highlight: pygments
    theme: spacelab
---

<br>

#### IMPORTANT: If the analysis is completed using software other than R, or not written up using R Markdown, the project should receive a 0 regardless of its content.

<br>

## Part 1: Data (3 points)

- 2 pt for correct reasoning for generabizability -- Answer should discuss whether 
random sampling was used. Learners might discuss any reservations, those should be well justified.

- 1 pt for correct reasoning for causality -- Answer should discuss whether 
random assignment was used.

## Part 2: Research questions (11 points)

- 3 pts for each research question (x 3)
    + Should be phrased in a non-causal way (1 pt)
    + Should be well defined / not vague (1 pt)
    + Is clear why this is of interest to the author / audience (1 pt)

- 2 pts for at least two of the questions involving three variables
    
## Part 3: EDA (30 points)

10 pts for each for each research question (x 3) 

- 3 pts for plots
    + Plots should address the research questions (1 pt)
    + Plots should be constructed correctly (1 pt)
    + Plots should be formatted well -- size not too large, not too small, etc. (1 pt)

- 3 pts for summary statistics
    + Summary statistics should address the research questions (1 pt)
    + Summary statistics should be calculated correctly (1 pt)
    + Summary statistics should be formatted well -- not taking up pages and pages, etc. (1 pt)
    
- 4 pts for narrative
    + Each plot and/or R output should be accompanied by a narrative (1 pt)
    + Narrative should interpret the visuals / R output correctly (2 pts)
    + Narrative should address the research question (1 pts)
  
## Overall (6 points)

- Uploaded HTML document resulting from the Rmd template: 1 pt
- Organization: 1 pts
- Readability of the text: 2 pts
- Readability of the code: 2 pts